version: "1.0"
services:
  api2_tw:
    build: .
    ports:
      - "3864:3864"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin